version: '3.9'
services:
  client:
    image: chatgpt-openai-client:latest
    build:
      context: client
    ports:
      - 8000:80
    environment:
      - SERVER=sever:5000
  server:
    image: chatgpt-openai-server:latest
    build:
      context: server
    ports:
      - 9000:5000
    env_file:
      - .env
